CREATE TABLE movies(
   id           INTEGER PRIMARY KEY auto_increment
  ,title        VARCHAR(28) NOT NULL
  ,year         VARCHAR(9) NOT NULL
  ,rated        VARCHAR(5) NOT NULL
  ,released     VARCHAR(11) NOT NULL
  ,runtime      VARCHAR(7) NOT NULL
  ,genre        VARCHAR(26) NOT NULL
  ,director     VARCHAR(17) NOT NULL
  ,writer       VARCHAR(170) NOT NULL
  ,actors       VARCHAR(76) NOT NULL
  ,plot         VARCHAR(246) NOT NULL
  ,language     VARCHAR(39) NOT NULL
  ,country      VARCHAR(26) NOT NULL
  ,awards       VARCHAR(66) NOT NULL
  ,poster       VARCHAR(136) NOT NULL
  ,meta_score    VARCHAR(3) NOT NULL
  ,imdb_rating   VARCHAR(3) NOT NULL
  ,imdb_votes    VARCHAR(9) NOT NULL
  ,imdb_id       VARCHAR(9) NOT NULL
  ,type         VARCHAR(6) NOT NULL
  ,total_seasons INTEGER 
  ,coming_soon   VARCHAR(4)
) auto_increment = 67002356;
INSERT INTO movies(title,year,rated,released,runtime,genre,director,writer,actors,plot,language,country,awards,poster,metascore,imdb_rating,imdb_votes,imdb_id,type,total_seasons,coming_soon) VALUES
 ('Avatar','2009','PG-13','18 Dec 2009','162 min','Action, Adventure, Fantasy','James Cameron','James Cameron','Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang','A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.','English, Spanish','USA, UK','Won 3 Oscars. Another 80 wins & 121 nominations.','https://c4.wallpaperflare.com/wallpaper/123/991/646/avatar-blue-skin-james-cameron-s-movie-avatar-movie-poster-wallpaper-preview.jpg','83','7.9','890,617','tt0499549','movie',NULL,NULL),
('I Am Legend','2007','PG-13','14 Dec 2007','101 min','Drama, Horror, Sci-Fi','Francis Lawrence','Mark Protosevich (screenplay), Akiva Goldsman (screenplay), Richard Matheson (novel), John William Corrington, Joyce Hooper Corrington','Will Smith, Alice Braga, Charlie Tahan, Salli Richardson-Whitfield','Years after a plague kills most of humanity and transforms the rest into monsters, the sole survivor in New York City struggles valiantly to find a cure.','English','USA','9 wins & 21 nominations.','https://w0.peakpx.com/wallpaper/159/97/HD-wallpaper-i-am-legend-dog-movie-new.jpg','65','7.2','533,874','tt0480249','movie',NULL,NULL),
('300','2006','R','09 Mar 2007','117 min','Action, Drama, Fantasy','Zack Snyder','Zack Snyder (screenplay), Kurt Johnstad (screenplay), Michael Gordon (screenplay), Frank Miller (graphic novel), Lynn Varley (graphic novel)','Gerard Butler, Lena Headey, Dominic West, David Wenham','King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.','English','USA','16 wins & 42 nominations.','https://images.alphacoders.com/626/thumb-440-626328.webp','52','7.7','611,046','tt0416449','movie',NULL,NULL),
('The Avengers','2012','PG-13','04 May 2012','143 min','Action, Sci-Fi, Thriller','Joss Whedon','Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)','Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth','Earth''s mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.','English, Russian','USA','Nominated for 1 Oscar. Another 34 wins & 75 nominations.','https://wallpapers.com/images/high/dope-avengers-wallpaper-4i9b267346ucs17k.webp','69','8.1','1,003,301','tt0848228','movie',NULL,NULL),
('The Wolf of Wall Street','2013','R','25 Dec 2013','180 min','Biography, Comedy, Crime','Martin Scorsese','Terence Winter (screenplay), Jordan Belfort (book)','Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey','Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.','English, French','USA','Nominated for 5 Oscars. Another 35 wins & 154 nominations.','https://c4.wallpaperflare.com/wallpaper/709/647/774/the-wolf-of-wall-street-leonardo-dicaprio-bent-over-high-heels-wallpaper-preview.jpg','75','8.2','786,985','tt0993846','movie',NULL,NULL),
('Interstellar','2014','PG-13','07 Nov 2014','169 min','Adventure, Drama, Sci-Fi','Christopher Nolan','Jonathan Nolan, Christopher Nolan','Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow','A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.','English','USA, UK','Won 1 Oscar. Another 39 wins & 134 nominations.','https://c4.wallpaperflare.com/wallpaper/527/320/1017/interstellar-movie-movies-astronaut-sea-wallpaper-preview.jpg','74','8.6','937,412','tt0816692','movie',NULL,NULL),
('Game of Thrones','2011–','TV-MA','17 Apr 2011','56 min','Adventure, Drama, Fantasy','N/A','David Benioff, D.B. Weiss','Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington','While a civil war brews between several noble families in Westeros, the children of the former rulers of the land attempt to rise up to power. Meanwhile a forgotten race, bent on destruction, plans to return after thousands of years in the North.','English','USA, UK','Won 1 Golden Globe. Another 185 wins & 334 nominations.','https://c4.wallpaperflare.com/wallpaper/474/430/502/game-of-thrones-daenerys-targaryen-wallpaper-preview.jpg','N/A','9.5','1,046,830','tt0944947','series',7,NULL),
('Vikings','2013–','TV-14','03 Mar 2013','44 min','Action, Drama, History','N/A','Michael Hirst','Travis Fimmel, Clive Standen, Gustaf Skarsgård, Katheryn Winnick','The world of the Vikings is brought to life through the journey of Ragnar Lothbrok, the first Viking to emerge from Norse legend and onto the pages of history - a man on the edge of myth.','English, Old English, Norse, Old, Latin','Ireland, Canada','Nominated for 7 Primetime Emmys. Another 17 wins & 49 nominations.','https://c4.wallpaperflare.com/wallpaper/783/785/107/ragnar-lodbrok-the-vikings-travis-fimmel-wallpaper-preview.jpg','N/A','8.6','198,041','tt2306299','series',5,NULL),
('Gotham','2014–','TV-14','01 Aug 2014','42 min','Action, Crime, Drama','N/A','Bruno Heller','Ben McKenzie, Donal Logue, David Mazouz, Sean Pertwee','The story behind Detective James Gordon''s rise to prominence in Gotham City in the years before Batman''s arrival.','English','USA','Nominated for 4 Primetime Emmys. Another 3 wins & 22 nominations.','https://c4.wallpaperflare.com/wallpaper/121/873/89/batman-artwork-concept-art-gotham-city-wallpaper-preview.jpg','N/A','8.0','133,375','tt3749900','series',3,NULL),
('Power','2014–','TV-MA','N/A','50 min','Crime, Drama','N/A','Courtney Kemp Agboh','Omari Hardwick, Joseph Sikora, Andy Bean, Lela Loren','James "Ghost" St. Patrick, a wealthy New York night club owner who has it all, catering for the city''s elite and dreaming big, lives a double life as a drug kingpin.','English','USA','1 win & 6 nominations.','https://c4.wallpaperflare.com/wallpaper/2/172/54/video-games-video-game-art-tower-horse-wallpaper-preview.jpg','N/A','8.0','14,770','tt3281796','series',3,NULL),
('Narcos','2015–','TV-MA','28 Aug 2015','49 min','Biography, Crime, Drama','N/A','Carlo Bernard, Chris Brancato, Doug Miro, Paul Eckstein','Wagner Moura, Boyd Holbrook, Pedro Pascal, Joanna Christie','A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar.','English, Spanish','USA','Nominated for 2 Golden Globes. Another 4 nominations.','https://c4.wallpaperflare.com/wallpaper/602/928/953/drugs-money-bullet-narcos-hd-wallpaper-preview.jpg','N/A','8.9','118,680','tt2707408','series',2,NULL),
('Breaking Bad','2008–2013','TV-14','20 Jan 2008','49 min','Crime, Drama, Thriller','N/A','Vince Gilligan','Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris','A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family''s financial future.','English, Spanish','USA','Won 2 Golden Globes. Another 132 wins & 218 nominations.','https://c4.wallpaperflare.com/wallpaper/697/957/83/breaking-bad-wallpaper-preview.jpg','N/A','9.5','889,883','tt0903747','series',5,NULL),
('Doctor Strange','2016','N/A','04 Nov 2016','N/A','Action, Adventure, Fantasy','Scott Derrickson','Scott Derrickson (screenplay), C. Robert Cargill (screenplay), Jon Spaihts (story by), Scott Derrickson (story by), C. Robert Cargill (story by), Steve Ditko (comic book)','Rachel McAdams, Benedict Cumberbatch, Mads Mikkelsen, Tilda Swinton','After his career is destroyed, a brilliant but arrogant and conceited surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.','English','USA','N/A','https://c4.wallpaperflare.com/wallpaper/823/649/247/doctor-strange-2016-movies-4k-8k-wallpaper-preview.jpg','N/A','N/A','N/A','tt1211837','movie',NULL,'TRUE'),
('Rogue One: A Star Wars Story','2016','N/A','16 Dec 2016','N/A','Action, Adventure, Sci-Fi','Gareth Edwards','Chris Weitz (screenplay), Tony Gilroy (screenplay), John Knoll (story), Gary Whitta (story), George Lucas (characters)','Felicity Jones, Riz Ahmed, Mads Mikkelsen, Ben Mendelsohn','The Rebellion makes a risky move to steal the plans to the Death Star, setting up the epic saga to follow.','English','USA','1 nomination.','https://c4.wallpaperflare.com/wallpaper/53/481/282/rogue-one-a-star-wars-story-star-wars-jyn-erso-movies-wallpaper-preview.jpg','N/A','N/A','N/A','tt3748528','movie',NULL,'TRUE'),
('Assassin''s Creed','2016','N/A','21 Dec 2016','N/A','Action, Adventure, Fantasy','Justin Kurzel','Bill Collage (screenplay), Adam Cooper (screenplay), Michael Lesslie (screenplay)','Michael Fassbender, Michael Kenneth Williams, Marion Cotillard, Jeremy Irons','When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society.','English','UK, France, USA, Hong Kong','N/A','https://c4.wallpaperflare.com/wallpaper/544/99/803/altair-assassin-039-s-creed-wallpaper-preview.jpg','N/A','N/A','N/A','tt2094766','movie',NULL,'TRUE'),
('Luke Cage','2016–','TV-MA','30 Sep 2016','55 min','Action, Crime, Drama','N/A','Cheo Hodari Coker','Mahershala Ali, Mike Colter, Frankie Faison, Erik LaRay Harvey','Given superstrength and durability by a sabotaged experiment, a wrongly accused man escapes prison to become a superhero for hire.','English','USA','N/A','https://c4.wallpaperflare.com/wallpaper/181/92/867/defenders-the-defenders-luke-cage-jessica-jones-matt-murdock-hd-wallpaper-preview.jpg','N/A','N/A','N/A','tt3322314','series',1,'TRUE');


select * from movies;